version: "3"
services:
  ducoproxy:
    env_file:
      - .env
    image: marcelop67/ducoproxy:latest
    build: .
    container_name: ducoproxy
    network_mode: bridge
    ports:
      - 5000:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true    
